apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-seeder
  namespace: vault
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-seeder
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      serviceAccountName: vault-seeder
      containers:
        - name: seeder
          image: hashicorp/vault:1.15
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "root"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Vault to be ready..."
              until vault status 2>/dev/null | grep -q "Key Value"; do sleep 2; done
              vault kv put secret/student-api/db username='postgres' password='supersecretpassword' dbname='student_db'
              echo "Vault seeded successfully!"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: OnFailure