services:
  postgres:
    image: postgres:16-alpine@sha256:93d55776e04376e19adb2733e3ccebb4392ee7dd86d8ff238503b30fe719c84f
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["./migrate"]
    command: ["up"]
    env_file: ".env"
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    env_file: ".env"
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  pgdata:
