apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "student-api.fullname" . }}-config
  labels:
    {{- include "student-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.configMap.PORT | quote }}
  DB_HOST: {{ .Values.configMap.DB_HOST | quote }}
  DB_PORT: {{ .Values.configMap.DB_PORT | quote }}
  DB_SSLMODE: {{ .Values.configMap.DB_SSLMODE | quote }}