apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    argocd.argoproj.io/depends-on: prometheus
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 11.10.0
    helm:
      values: |
        config:
          modules:
            http_2xx:
              http:
                preferred_ip_protocol: ip4
              prober: http

        nodeSelector:
          type: dependent_services

        serviceMonitor:
          enabled: true
          interval: 30s
          namespace: observability
          labels:
            release: prometheus

        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m