apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/depends-on: prometheus
spec:
  project: default
  source:
    repoURL: https://github.com/steamban/one2n-sre-bootcamp.git
    targetRevision: feat/argocd
    path: argocd/apps/observability/config
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
