apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/depends-on: prometheus
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.0.0
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          rulerConfig:
            alertmanager_url: http://prometheus-kube-prometheus-alertmanager.observability.svc:9093
            storage:
              type: local
              local:
                directory: /rules
            rule_path: /tmp/scratch
            ring:
              kvstore:
                store: inmemory
        singleBinary:
          replicas: 1
          extraVolumes:
            - name: rules
              configMap:
                name: loki-alert-rules
          extraVolumeMounts:
            - name: rules
              mountPath: /rules/fake/rules.yaml
              subPath: rules.yaml
          persistence:
            enabled: true
            size: 10Gi
          nodeSelector:
            type: dependent_services
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        gateway:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
