apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alert-rules
  namespace: observability
data:
  rules.yaml: |
    groups:
      - name: log-alerts
        rules:
          - alert: HighErrorRate
            expr: sum by (namespace) (rate({namespace="student-api"} |= "error" [10m])) > 0.1
            annotations:
              summary: "High error rate in {{ $labels.namespace }}"
