apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: secret/observability/slack
        property: webhook_url
