apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "student-api.fullname" . }}-vault-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ include "student-api.fullname" . }}-vault-token
          key: token
