apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-setup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/depends-on: eso
spec:
  project: default
  source:
    repoURL: https://github.com/steamban/one2n-sre-bootcamp.git
    targetRevision: feat/argocd
    path: argocd/apps/vault-setup-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m