apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-seeder
  namespace: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-seeder
  namespace: external-secrets
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-seeder
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault-seeder
      containers:
        - name: seeder
          image: hashicorp/vault:1.15
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "root"
          command:
            - /bin/sh
            - -c
            - |
              vault kv put secret/student-api/db username='postgres' password='supersecretpassword' dbname='student_db'
          securityContext:
            runAsUser: 100
      restartPolicy: OnFailure