name: CI Pipeline

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Code Linting
        run: |
          make fmt
          make vet

  build:
    name: Build
    needs: [lint]
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Build API
        run: make build

  test:
    name: Test
    needs: [lint]
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: make test

  security-scan:
    name: Security Scan
    needs: [lint]
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2026.1
          staticcheck ./...